### ISSUE TITLE
InvMenu::TYPE_DOUBLE_CHEST does not work

### ISSUE THREAD

**Issue by Muqsit** [Muqsit/InvMenu#1]
This hasn't been correctly implemented due to the slight complexity that double chests offer.

**Comment by Bruno1069** [comment]
Question

How to do when the player clicks an item in Inv Menu the Menu close?

**Comment by Muqsit** [comment]
@Bruno1069
```php
/** @var InvMenu $menu */
$menu->setListener(function(Player $player, Item $item1, Item $item2, SlotChangeAction $invAction) : bool{
    $player->removeWindow($invAction->getInventory());
});
```

**Comment by Bruno1069** [comment]
Thanks

**Comment by alair069** [comment]
![image](https://user-images.githubusercontent.com/27539870/35755914-553dae2c-0850-11e8-9773-12569c10124f.png)

Is not setListener?

**Comment by Muqsit** [comment]
@alair069 thanks, but please open a new issue next time 👍 
https://github.com/Muqsit/InvMenu/commit/b6cc5363338285155de0cf7842e35a4eb910d280
