### ISSUE TITLE
Trading inventory

### ISSUE THREAD

**Issue by ghost** [Muqsit/InvMenu#10]
Is it possible to create such a inventory?
![kek](https://d1u5p3l4wpay3k.cloudfront.net/minecraft_gamepedia/thumb/4/49/Trading_paper_clean_GUI.png/200px-Trading_paper_clean_GUI.png?version=542510dbaa4159c47e905b5e924b2d0a)

**Comment by Muqsit** [comment]
*intensified thinking*

**Comment by SuperMaXAleX** [comment]
![thinking muq](https://user-images.githubusercontent.com/19352571/36595289-e534d6ca-18a1-11e8-8630-6a996ed25d99.png)

**Comment by MalakasPlayzMC** [comment]
@Muqsit Because I don't want to create an issue for stupid things, plugin.yml is missing

**Comment by zyware** [comment]
@MalakasPlayzMC Ahahah, the plugin has moved to support virion

**Comment by MalakasPlayzMC** [comment]
Sorry then

**Comment by TheAz928** [comment]
This might be possible by creating a villager at x vector (all components must be int), then making it invisible, generate nametags and then send the packet (trading packet) to the player

**Comment by Muqsit** [comment]
Closing this issue.
Trading inventories aren't handled the same way other inventories are. This can't be done without aggressively modifying incoming InventoryTransactionPackets. Anyway, it's much better for a separate plugin to handle that mess than for a virion. Registering events through virions is messy enough already.
