### ISSUE TITLE
Custom item class doen't work

### ISSUE THREAD

**Issue by xxAROX** [Muqsit/InvMenu#107]
My item-class:
*StimoPlayer extends Player*
![grafik](https://user-images.githubusercontent.com/57589973/98314346-0f97c880-1fd6-11eb-8a19-74000a4afbbd.png)

Method:
![grafik](https://user-images.githubusercontent.com/57589973/98314521-6d2c1500-1fd6-11eb-8eee-be12e2dadedc.png)

**Comment by Muqsit** [comment]
This isn't a bug with InvMenu but the behaviour of moving items between pocketmine inventories. Items may be recreated, serialized and deserialized in-between, stripping away the custom properties stored in item classes. That approach of dealing with custom item properties is flawed. You should store data inside NBT tags and work with it.

A way to validate this is check if `$item` and `Item::nbtDeserialize($item->nbtSerialize())` are equal.

**Comment by xxAROX** [comment]
kk
