### ISSUE TITLE
Construct Error

### ISSUE THREAD

**Issue by Dapro718** [Muqsit/InvMenu#108]
TypeError: "Argument 1 passed to Dapro718\Warps\libs\muqsit\invmenu\InvMenu::__construct() must be an instance of Dapro718\Warps\libs\muqsit\invmenu\metadata\MenuMetadata, null given, called in phar:///home/minecraft-pe/server/plugins/Warps_dev-8.phar/src/Dapro718/Warps/libs/muqsit/invmenu/InvMenu.php on line 40" (EXCEPTION) in "plugins/Warps_dev-8.phar/src/Dapro718/Warps/libs/muqsit/invmenu/InvMenu" at line 74
[22:26:09] [Server thread/CRITICAL]: #0 plugins/Warps_dev-8.phar/src/Dapro718/Warps/libs/muqsit/invmenu/InvMenu(40): Dapro718\Warps\libs\muqsit\invmenu\InvMenu->__construct(NULL )

$this->menu = InvMenu::create(InvMenu::TYPE_CHEST);

**Comment by Muqsit** [comment]
This occurs when InvMenu::create() is called before InvMenuHandler::register().
