### ISSUE TITLE
Inventory Close

### ISSUE THREAD

**Issue by PixelzChris** [Muqsit/InvMenu#112]
I created a gui menu but now with 1.16 i cant close it...
I use 
`public function onInventoryTransactionEvent(InventoryTransactionEvent $event){`
`$action = $event->getTransaction()->getActions();`
`$player = $event->getTransaction()->getSource();`
`$item = null;`
`foreach ($action as $inventoryAction) {`
`foreach ($event->getTransaction()->getInventories() as $inventory) {`
`$item = $inventoryAction->getTargetItem();`
`if ($item->getName() == "Close Menu"){`
`$player->sendMessage("test");`
`$player->removeWindow($action->getInventory());` this code
`}`

if i use `$player->removeWindow($action->getInventory());` i get an error (this was working before 1.16
if i use `$player->removeWindow($this->menu->getInventory());` i can close the gui but if i want to open another one the gui doesnt appear but if i look behind the chest has spawned...

Note that everything was working before 1.16 and i also looked up at the examples but couldnt find solution

**Comment by Muqsit** [comment]
What is it that you're trying to do? And what are the errors you're getting?
