### ISSUE TITLE
Gui close

### ISSUE THREAD

**Issue by PixelzChris** [Muqsit/InvMenu#113]
Check the code i use on #112 
This is my issue
https://github.com/pmmp/PocketMine-MP/issues/3741 but in this forum there is not any answer of solving the problem

**Comment by Muqsit** [comment]
Yeah, this is a known issue with the client.
The client doesn't show forms when an inventory is open, you have to use the `then()` method for this, documented in the wiki: https://github.com/Muqsit/InvMenu/wiki/Examples---InvMenu-v4#precautions
