### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PechenkaPM** [Muqsit/InvMenu#119]
how can i tell if a player has dragged an item from their inventory to the menu or vice versa?

**Comment by Muqsit** [comment]
Check the source items. I would assume dragging would imply there are two actions occurring in the transaction — item from a player slot moves to a menu slot and item from a menu slot moves to a player slot.
```php
$menu->setListener(function(InvMenuTransaction $transaction) : InvMenuTransactionResult{
	$actions = $transaction->getTransaction()->getActions();
	if(count($actions) === 2){
		$action = $transaction->getAction();
		unset($actions[array_search($action, $actions, true)]);
		$other_action = current($actions);
		if($other_action instanceof SlotChangeAction){
			$player_inventory = $other_action->getInventory();
			if($player_inventory instanceof PlayerCursorInventory || $player_inventory instanceof PlayerInventory){
				$who = $transaction->getPlayer()->getName();
				echo $who, " moved ", $other_action->getSourceItem(), " from their inventory to menu inventory", PHP_EOL;
				echo $who, " moved ", $action->getSourceItem(), " from menu inventory to their inventory", PHP_EOL;
			}
		}
	}
	return $transaction->continue();
});
```
However, the code above will give you correct item count values only if you moved an item _from_ or an item _to_ an empty slot. If you'd like to get the exact item count of the items that are being dragged, you'd need to do some logical calculations between source and target items for each action of the transaction.
It comes down to the logic behind the mechanism you're trying to implement. What is it that you're working on?
