### ISSUE TITLE
Read 

### ISSUE THREAD

**Issue by MrReskill** [Muqsit/InvMenu#12]
The function $menu->readOnly(); won't work !

**Comment by MrReskill** [comment]
@Muqsit $menu->readOnly(); won't work with pmmp beta 1.2.13.5

**Comment by Muqsit** [comment]
pmmp doesn't have a beta version or a 1.2.13.5 version

**Comment by MrReskill** [comment]
In branch mcpebeta-clusterfuck !

**Comment by Muqsit** [comment]
InvMenu doesn't support that branch and you're not supposed to use that branch for production.
