### ISSUE TITLE
Transaction issue

### ISSUE THREAD

**Issue by celishere** [Muqsit/InvMenu#120]
The code for the menu was taken from the examples and has not been changed.

![image](https://user-images.githubusercontent.com/54947469/103795285-d66fe900-5056-11eb-84ac-2c8e3bf3b2bc.png)

Problem: when I do an action after which another menu should open-nothing happens. If after that I want to open any other menu (even the same one) nothing will happen, only a fake block will appear.

![image](https://user-images.githubusercontent.com/54947469/103795628-441c1500-5057-11eb-9c87-78f21c409327.png)

**Comment by PixelzChris** [comment]
Same happens to me every time i close the inventory through code (any type of closing inventory code + the one given in examples and in readme.txt the gui windows dont work anymore.

If i click the x in top right of the inventory it wont have problem but we need to open an inventory after clicking an inventory item.

Tested in local host!

**Comment by celishere** [comment]
@PixelzChris 

I also do not have any problems when closing the inventory through the cross.

I also work on a local server.

**Comment by Muqsit** [comment]
@celishere Please share your code here.

**Comment by celishere** [comment]
class Example{

	/** @var InvMenu */
	private $menu1;

	/** @var InvMenu */
	private $menu2;

	public function __construct(string $menu1name, string $menu2name){
		$this->menu1 = InvMenu::create(InvMenu::TYPE_CHEST)
			->setName($menu1name)
 			->setListener(InvMenu::readonly(Closure::fromCallable([$this, "onUseFirstMenu"])));
		$this->menu1->getInventory()->addItem(Item::get(Item::DIAMOND)->setCustomName(TextFormat::RED . "Click ME!"));

		$this->menu2 = InvMenu::create(InvMenu::TYPE_CHEST)
			->setName($menu2name)
			->setListener(InvMenu::readonly(Closure::fromCallable([$this, "onUseSecondMenu"])));
		$this->menu2->getInventory()->addItem(Item::get(Item::GOLD_INGOT)->setCustomName(TextFormat::RED . "Click ME!"));
	}

	public function onUseFirstMenu(DeterministicInvMenuTransaction $transaction) : void{
		$this->menu2->send($transaction->getPlayer());
	}

	public function onUseSecondMenu(DeterministicInvMenuTransaction $transaction) : void{
		$this->menu1->send($transaction->getPlayer());
	}

	public function sendTo(Player $player) : void{
		$this->menu1->send($player);
	}
}

$example = new Example("Menu #1", "Menu #2");

/** @var Player $player */
$example->sendTo($player);

**Comment by celishere** [comment]
I call it when I click on a certain block

**Comment by Muqsit** [comment]
@celishere I'm confused.
In the code above, I see no references to hoppers. However, in the screenshot you shared, there's a hopper.
Are you sure you're using exactly that code?

**Comment by celishere** [comment]
A funnel is another interface that I try to open after actions with that chest whose code I threw you.

**Comment by PixelzChris** [comment]
> @celishere I'm confused.
> In the code above, I see no references to hoppers. However, in the screenshot you shared, there's a hopper.
> Are you sure you're using exactly that code?

Well code is not the problem local host is the problem... Most of us dont want to spend money on hosts and we use local host but your api does not work correctly

**Comment by celishere** [comment]
@PixelzChris 

I don't think the localhost is the problem.
I'll check your mind in a day.

**Comment by Muqsit** [comment]
@celishere Alright, I'll test the code in some time. However, I'd appreciate sharing the exact code so it becomes easier to reproduce this issue.
I remember testing some edge cases a while ago, leading to the following commit https://github.com/Muqsit/InvMenu/commit/893e2d14893431eccd96155cb9ee5a9f44373181.

**Comment by celishere** [comment]
@Muqsit 

Thank you. I'll post the code later.

**Comment by celishere** [comment]
Hi, @Muqsit 

Here`s the code

Main class: 

` /**
     * @param PlayerInteractEvent $event
     */
    public function onInteract(PlayerInteractEvent $event): void {
        if ($event->getBlock()->getId() === Block::ENCHANTING_TABLE) {
            $event->setCancelled();

            $example = new Example("Menu #1", "Menu #2");

            $example->sendTo($event->getPlayer());
        }
}`

Example class: 

`
<?php

declare(strict_types=1);

namespace EnchantAndRepair\gui;

use muqsit\invmenu\InvMenu;
use muqsit\invmenu\transaction\DeterministicInvMenuTransaction;

use pocketmine\Player;
use pocketmine\item\Item;
use pocketmine\utils\TextFormat;

use Closure;

/**
 * Class Example
 * @package EnchantAndRepair\gui
 * 
 * @version 1.0.0
 * @since   1.0.0
 */
class Example {

    /** @var InvMenu */
    private $menu1;

    /** @var InvMenu */
    private $menu2;

    public function __construct(string $menu1name, string $menu2name){
        $this->menu1 = InvMenu::create(InvMenu::TYPE_CHEST)
            ->setName($menu1name)
            ->setListener(InvMenu::readonly(Closure::fromCallable([$this, "onUseFirstMenu"])));
        $this->menu1->getInventory()->addItem(Item::get(Item::DIAMOND)->setCustomName(TextFormat::RED . "Click ME!"));

        $this->menu2 = InvMenu::create(InvMenu::TYPE_CHEST)
            ->setName($menu2name)
            ->setListener(InvMenu::readonly(Closure::fromCallable([$this, "onUseSecondMenu"])));
        $this->menu2->getInventory()->addItem(Item::get(Item::GOLD_INGOT)->setCustomName(TextFormat::RED . "Click ME!"));
    }

    public function onUseFirstMenu(DeterministicInvMenuTransaction $transaction) : void{
        $transaction->then(function(Player $player) : void{
            $this->menu2->send($player->getPlayer());
        });
    }

    public function onUseSecondMenu(DeterministicInvMenuTransaction $transaction) : void{
        $transaction->then(function(Player $player) : void{
            $this->menu1->send($player->getPlayer());
        });
    }

    public function sendTo(Player $player) : void{
        $this->menu1->send($player);
    }
}
`

**Comment by PixelzChris** [comment]
rip inv menu

**Comment by intagaming** [comment]
I have sort of similar problem. When using `$player->removeWindow()`, I can't open `PlayerInventory` by pressing E anymore (Win10, others untested).
My solution is using this code in `PlayerSession.php`:
```
    public function removeGraphic(): bool
    {
        if($this->current_menu !== null){
            $this->current_menu->getType()->removeGraphic($this->player, $this->menu_extradata);
            return true;
        }
        return false;
	}
```
This removes the fake block/title that responsible for the `InvMenuInventory`. I think this idea of solving problems involving `removeWindow()` is widely adopted long ago. It just so happens that until today I finally try to solve the problem (though the problem before is the game entirely _crashing_).

**Comment by Muqsit** [comment]
@intagaming If you think it's a different issue, you may open another issue instead. Also, a recording of what's happening would be appreciated.

**Comment by callumrawlinson** [comment]
@PixelzChris it's me for yolocraft

**Comment by PixelzChris** [comment]
> @PixelzChris it's me for yolocraft

Are you going to give me the money you try to charge back? (20$ the bridge plugin) you charge back second time

**Comment by Muqsit** [comment]
#162
