### ISSUE TITLE
Help needed please

### ISSUE THREAD

**Issue by callumrawlinson** [Muqsit/InvMenu#122]
Hello!

I am trying to make a hopper invmenu with the command /games which will open the menu up and there will be 5 slots
slot 1) game1
slot 2) game2
slot 3) game 3
slot 4) game 4
slot 5) tp to hub

is this possible. i tried but gave up after hundreds of errors.

**Comment by Muqsit** [comment]
Yes this is possible. Please provide the code you've used.

**Comment by callumrawlinson** [comment]
this i what i have got:

the only problem is i based it of another plugin which uses economyapi aswell which i dont need

`<?php

namespace callum;

use muqsit\invmenu\InvMenu;
use muqsit\invmenu\InvMenuHandler;
use muqsit\invmenu\inventories\BaseFakeInventory;

use pocketmine\plugin\PluginBase;

use pocketmine\event\Listener;

use pocketmine\Player;
use pocketmine\item\Item;

use pocketmine\command\Command;
use pocketmine\command\CommandSender;
use pocketmine\command\ConsoleCommandSender;

use pocketmine\event\player\PlayerInteractEvent;
use pocketmine\inventory\transaction\action\SlotChangeAction;
use pocketmine\event\inventory\InventoryTransactionEvent;

use pocketmine\utils\TextFormat as C;

class gamegui extends PluginBase implements Listener
{

    public function OnEnable()
    {
        $this->getLogger()->info(C::RED . C::BOLD . "This plugin made by" . C::DARK_PURPLE . " Callum Rawlinson " . C::RED . " From CRSTUDIOS studio" . C::WHITE . "\n-\n-\n-\n-\n-\n-\n-\n-" . C::BLUE . "COVID-19" . C::DARK_PURPLE . " WASH YOUR HANDS " . C::WHITE . "\n-\n-\n-\n-\n-\n-\n-\n-");
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
        if (!InvMenuHandler::isRegistered()) {
            InvMenuHandler::register($this);
        }
    }

    public function onCommand(CommandSender $sender, Command $cmd, string $label, array $args): bool
    {
        if ($cmd->getName() == "games") {
            if ($sender instanceof Player) {
                $this->gamemenu = InvMenu::create(InvMenu::TYPE_HOPPER);
                $this->gamemenu->readonly();
                $this->gamemenu->setName(C::BOLD . "Game Menu");
                //$kitSelect->setInventoryCloseListener([$this, 'closeInventory']);

                $this->gamemenu->getInventory()->setContents([
                    2 => Item::get(Item::DIAMOND_SWORD)->setCustomName(C::BOLD . C::DARK_BLUE . "Murder Mystery\n\n" . C::RESET . C::GREEN . "\n" . C::UNDERLINE . "Click To Join"),
                    4 => Item::get(Item::BOW)->setCustomName(C::BOLD . C::DARK_BLUE . "The Bridge\n\n" . C::RESET . C::GREEN . "\n" . C::UNDERLINE . "Click To Join"),
                    6 => Item::get(Item::ARROW)->setCustomName(C::BOLD . C::DARK_BLUE . "HotBlock\n\n" . C::RESET . C::GREEN . "\n" . C::UNDERLINE . "Click To Join"),
                    13 => Item::get(Item::DIAMOND)->setCustomName(C::BOLD . C::DARK_BLUE . "Hub\n\n" . C::RESET . C::GREEN . "\n" . C::UNDERLINE . "Click To Join"),
                    36 => Item::get(Item::STAINED_GLASS_PANE, 7 , 1)->setCustomName(" "),
                    37 => Item::get(Item::STAINED_GLASS_PANE, 7 , 1)->setCustomName(" "),
                    38 => Item::get(Item::STAINED_GLASS_PANE, 7 , 1)->setCustomName(" "),
                    39 => Item::get(Item::STAINED_GLASS_PANE, 7 , 1)->setCustomName(" "),
                    40 => Item::get(Item::STAINED_GLASS_PANE, 7 , 1)->setCustomName(" "),
                    41 => Item::get(Item::STAINED_GLASS_PANE, 7 , 1)->setCustomName(" "),
                    42 => Item::get(Item::STAINED_GLASS_PANE, 7 , 1)->setCustomName(" "),
                    43 => Item::get(Item::STAINED_GLASS_PANE, 7 , 1)->setCustomName(" "),
                    44 => Item::get(Item::STAINED_GLASS_PANE, 7 , 1)->setCustomName(" "),
                    48 => Item::get(Item::PAPER)->setCustomName(C::BOLD . C::DARK_BLUE . C::UNDERLINE . "Info\n\n" . C::RESET . C::WHITE . "This menu is made " . C::DARK_PURPLE . C::UNDERLINE . "BY CALLUM" . C::RESET . C::WHITE . " for you\nto choose games for a gui"),
                    49 => Item::get(Item::STAINED_GLASS, 14, 1)->setCustomName(C::RED . C::BOLD . "Close the menu\n\n" . C::RESET . C::YELLOW . "Click here!")
                ]);
			    
				$this->gamemenu->send($sender);
				                }
            }
        }
        return true;
    }

    public function onInventoryTransactionEvent(InventoryTransactionEvent $event)
    {
        $action = $event->getTransaction()->getActions();
        $player = $event->getTransaction()->getSource();
        //$player = $event->getPlayer();
        $money = EconomyAPI::getInstance()->myMoney($player);
        $item = null;

        foreach ($action as $inventoryAction) {
            foreach ($event->getTransaction()->getInventories() as $inventory) {
                $item = $inventoryAction->getTargetItem();

                if ($item->getName() == C::BOLD . C::DARK_BLUE . "Murder Mystery\n\n" . C::RESET . C::GREEN . "\n" . C::UNDERLINE . "Click To Join") {
                    {
                        $player->sendMessage(C::BOLD . "Joining Murder Mystery");
                        $this->getServer()->dispatchCommand(new ConsoleCommandSender(), 'rca "' . $player->getName() . '" mdr join MMHUB');
                        $this->getServer()->dispatchCommand($player, "mdr" . "join" . "MMHUB");
                        $this->getServer()->dispatchCommand(new ConsoleCommandSender(), 'rca "' . $player->getName() . '" mdr join MMHUB');
                        EconomyAPI::getInstance()->ReduceMoney($player, 0);
                        $event->setCancelled();
                    }
                }
                if ($item->getName() == C::BOLD . C::DARK_BLUE . "The Bridge\n\n" . C::RESET . C::GREEN . "\n" . C::UNDERLINE . "Click To Join") {
                    {
                        $player->sendMessage(C::BOLD . "Joining The Bridge");
                        $this->getServer()->dispatchCommand(new ConsoleCommandSender(), 'rca "' . $player->getName() . '" tb join');
                        $this->getServer()->dispatchCommand($player, "tb" . "join" . );
                        $this->getServer()->dispatchCommand(new ConsoleCommandSender(), 'rca "' . $player->getName() . '" tb join');
                        EconomyAPI::getInstance()->ReduceMoney($player, 0);
                        $event->setCancelled();
                    }
                }
				if ($item->getName() == C::BOLD . C::DARK_BLUE . "HotBlock\n\n" . C::RESET . C::GREEN . "\n" . C::UNDERLINE . "Click To Join") {
                    {
                        $player->sendMessage(C::BOLD . "Joining HotBlock");
                        $this->getServer()->dispatchCommand(new ConsoleCommandSender(), 'mw tp HotBlock "' . $player->getName() . '"');
                        $this->getServer()->dispatchCommand($player, "mw tp" . "HotBlock" . );
                        $this->getServer()->dispatchCommand(new ConsoleCommandSender(), 'mw tp HotBlock"' . $player->getName() . '" ');
                        EconomyAPI::getInstance()->ReduceMoney($player, 0);
                        $event->setCancelled();
                    }
                }
			}
		}
	}
}`

**Comment by callumrawlinson** [comment]
i want a hopper but couldnt find the thing for it so i had to use chest
but its not going to work :( unless you help i dont think

**Comment by callumrawlinson** [comment]
i based it off a taggui

**Comment by Muqsit** [comment]
@callumrawlinson Unfortunately, I wouldn't be able to help you with that. The code you sent has several PHP syntax errors, which in no way is related to InvMenu.

**Comment by callumrawlinson** [comment]
@Muqsit would you know how to make a hopper though like this?


> Hello!
> 
> I am trying to make a hopper invmenu with the command /games which will open the menu up and there will be 5 slots
> slot 1) game1
> slot 2) game2
> slot 3) game 3
> slot 4) game 4
> slot 5) tp to hub
> 
> is this possible. i tried but gave up after hundreds of errors.

**Comment by callumrawlinson** [comment]
![image](https://user-images.githubusercontent.com/72660075/105029847-c985c900-5a4a-11eb-84ca-174523961a0c.png)

or maybe like this @Muqsit

**Comment by Muqsit** [comment]
@callumrawlinson Yeah, you can refer to the InvMenu wiki which provides some examples that may be useful for your case.
https://github.com/Muqsit/InvMenu/wiki
