### ISSUE TITLE
Stained objects

### ISSUE THREAD

**Issue by callumrawlinson** [Muqsit/InvMenu#125]
Hello @Muqsit ,

Do you know hot to put a stained glass pane in a doublechest inv menu as i dont know how the item ids work

the item i want is stained_glass_pane 
and the colour i want would be 14 
so it would be stained_glass_pane 14 right? 
how would i put this in a inv menu

**Comment by Muqsit** [comment]
You can refer to the wiki, it's the same procedure as putting any item in a player inventory.
