### ISSUE TITLE
How to set non-readonly on specific slot?

### ISSUE THREAD

**Issue by xxAROX** [Muqsit/InvMenu#133]
```php
		$this->menu->setListener(function (InvMenuTransaction $transaction): InvMenuTransactionResult{
			if ($transaction->getAction()->getSlot() == self::ACTION_SLOT/*13*/) {
				return $transaction->continue();
			}
			$result = $transaction->discard();
			$this->callFunctionalItem(new DeterministicInvMenuTransaction($transaction, $result));
			(Closure::fromCallable([$this, "onClick"]))($transaction, $transaction->getPlayer(), $transaction->getItemClicked(), $transaction->getItemClickedWith());
			return $result;
		});
```

Thats dosn't work..

**Comment by xxAROX** [comment]
I'm using normal invmenu without changes from my side

**Comment by Muqsit** [comment]
> Thats dosn't work..

Can you elaborate what you mean by it?

I don't understand why you're passing the callback the transaction instance as well as values returned by methods of the transaction — seems unnecessary.

**Comment by xxAROX** [comment]
i wanna make an auctionhouse plugin be like hypixel, but on create the item what I'm put into the slot 13 it should be not readonly, but these other items should be readonly.

**Comment by Muqsit** [comment]
This is a little tricky as pocketmine doesn't pave a way to modify items within a transaction.
Until that is possible, I suppose you could allow the transaction to happen on slot 13, and take an action during inventory close.
```php
$menu->setListener(function(InvMenuTransaction $txn) : InvMenuTransactionResult{
	if($txn->getAction()->getSlot() === 13){
		$txn->getInventory()->setItem($txn->getSlot(), $txn->getIn());
		$txn->getPlayer()->removeWindow($txn->getInventory()); // calls inventory close listener
		return $transaction->continue();
	}
	return $transaction->discard();
})->setInventoryCloseListener(function(Player $player, Inventory $inventory) : void{
	$item = $inventory->getItem(13);
	if(!$item->isNull()){
		// do something with item
	}
});
```

Or another possible alternative is to have a "Hold the item you'd like to auction."

Anyway, if you simply want to set slot 13 as non-readonly, you can discard the transaction for any other slot.
```php
$menu->setListener(function(InvMenuTransaction $txn) : InvMenuTransactionResult{
	if($txn->getAction()->getSlot() === 13){
		return $transaction->continue(); // allow transaction
	}
	return $transaction->discard(); // cancel transaction
})
```

**Comment by xxAROX** [comment]
i cant use the first one, because the player can customize starting price & duration and the second oine doesn't work

**Comment by Muqsit** [comment]
@xxAROX  It seems to be working as intended in my case, although I am not sure what your definition of working is here.

**Comment by xxAROX** [comment]
working:
 - You can pick / insert item on slot 13, but on every other slot you cant

**Comment by xxAROX** [comment]
https://user-images.githubusercontent.com/57589973/109974650-10c5d180-7cfa-11eb-9961-39556f40c296.mp4

**Comment by callumrawlinson** [comment]
Not to be mean but i would just use another ah or even muqsits chest shop plugin.You could adapt one aswell and see what they have done

**Comment by callumrawlinson** [comment]
![oof](https://user-images.githubusercontent.com/72660075/109977431-b8d89c00-7cf4-11eb-9468-f7c383237966.png)

**Comment by xxAROX** [comment]
haha
i'll look

**Comment by xxAROX** [comment]
Hmmm, i did `setListener(null);`
Now:

https://user-images.githubusercontent.com/57589973/109982254-027bb380-7d02-11eb-8309-b562234af302.mp4

**Comment by xxAROX** [comment]
i reopen if i need help again :)
