### ISSUE TITLE
readonly() Bug

### ISSUE THREAD

**Issue by zyware** [Muqsit/InvMenu#14]
Function readonly() not work on TYPE_HOPPER

**Comment by zyware** [comment]
$menu = InvMenu::create(InvMenu::TYPE_HOPPER)->readonly()->sessionize();
$menu->send($sender);

**Comment by zyware** [comment]
Maybe I need to use my class?

**Comment by zyware** [comment]
I'm using PluginTask for setItem()

**Comment by zyware** [comment]
![default](https://user-images.githubusercontent.com/34810680/37253180-4e1e2ade-253f-11e8-9b52-6426f390975b.png)

**Comment by zyware** [comment]
I want the player not to take the item.

**Comment by Muqsit** [comment]
Hm, you definitely aren't using TYPE_HOPPER in the screenshot

**Comment by Muqsit** [comment]
I can't reproduce this, I've done the following tests: https://gist.github.com/Muqsit/8154dac28a85c71c46f6b42a0d55df41 and it works fine.
