### ISSUE TITLE
ps4 players do not receive inventory

### ISSUE THREAD

**Issue by Refaltor77** [Muqsit/InvMenu#141]
Hello! 
Ducoup when I try to send an inventory to a ps4 player, nothing just happens

**Comment by BrahmjotSingh0** [comment]
Same issue

**Comment by Muqsit** [comment]
I currently do not have access to my PS4 but I would appreciate if someone can test whether this problem still exists (on branch `4.0`), and if it does, see if running the following code in plugin's `onEnable` solves this issue for InvMenus sent by that plugin.
```php
// PluginBase scope
protected function onEnable() : void{
	if(!InvMenuHandler::isRegistered()){
		InvMenuHandler::register($this);
	}

	// use pocketmine\network\mcpe\protocol\types\DeviceOS;
	$registry = InvMenuHandler::getPlayerManager()->getNetworkHandlerRegistry();
	$registry->register(DeviceOS::PLAYSTATION, $registry->get(DeviceOS::UNKNOWN));
}
```

**Comment by Muqsit** [comment]
Can confirm this is working fine on PlayStation.
