### ISSUE TITLE
Custom Lore

### ISSUE THREAD

**Issue by reactwindd** [Muqsit/InvMenu#148]
Able to add custom lore, Example:

$menu->getInventory()->addItem(ItemFactory::get(ItemIds::DIAMOND_SWORD)->setCustomLore('§6This is a Custom Lore!'))

**Comment by Muqsit** [comment]
Yes, that is possible.

**Comment by reactwindd** [comment]
do u mean of its possible to do rn or next update?

**Comment by Muqsit** [comment]
`$menu->getInventory()` returns a `pocketmine\inventory\Inventory` instance, so you can add items into it just like you could into any other pocketmine inventory.
