### ISSUE TITLE
how to setName() in TYPE_HOPPER?

### ISSUE THREAD

**Issue by zyware** [Muqsit/InvMenu#15]

**Comment by Muqsit** [comment]
Yeah, the custom name on hoppers doesn't really work, don't know why.

**Comment by MalakasPlayzMC** [comment]
PocketMine bug?

**Comment by Muqsit** [comment]
Actually, no. PocketMine doesn't have hoppers and InvMenu only uses PocketMine's BaseInventory class for sending the GUI, no Tile stuff.

I have a feeling you need to delay the hopper time just like double chest inventories do.

**Comment by Muqsit** [comment]
Mojang fixed this in 1.7
