### ISSUE TITLE
How to load the plugin

### ISSUE THREAD

**Issue by iZeaoGamer** [Muqsit/InvMenu#16]
Hey, I was wondering how to load the InvMenu plugin. I've created a virions folder, and added DEVirion and InvMenu to the virions plugin, and it never loads into the server. Any solutions? Thanks.

**Comment by Muqsit** [comment]
InvMenu must be added to the `virions/` folder, not the `plugins/` folder.
This should help: https://github.com/poggit/devirion

**Comment by iZeaoGamer** [comment]
I already put it in that folder, and it never loads.

**Comment by iZeaoGamer** [comment]
Here’s the pictures that I did it right:
![4742bf19-125d-4540-9515-04826fb4bf02](https://user-images.githubusercontent.com/20418886/38194751-72f2e37a-3671-11e8-8e63-794b214536e3.png)
![f365e3d7-875a-4005-a27d-fe926ab60a80](https://user-images.githubusercontent.com/20418886/38194752-730f6aea-3671-11e8-92ce-2568a7046d13.png)
