### ISSUE TITLE
Trying to open a GUI from another plugin by using a menu made in another plugin

### ISSUE THREAD

**Issue by EmporiumDevelopment** [Muqsit/InvMenu#160]
I am making a player menu plugin, it has multiple options like open ender chest, teleport to places etc, but when i try to dispatchcommand to open another menu i hear the other menu open but it doesnt open on screen.

heres my code
https://www.codepile.net/pile/XNyg4mYb

**Comment by Muqsit** [comment]
See if dispatching the command without calling `Player::removeWindow()`  makes it work... comment out all `$sender->removeWindow($inventory);` (might be a similar issue as https://github.com/Muqsit/InvMenu/issues/116).
