### ISSUE TITLE
Not to sure if this is a issue or a fault on my behalf?

### ISSUE THREAD

**Issue by Azikk024** [Muqsit/InvMenu#161]
I have creates a invmenu and it works fine but then when pressing a item to open the next invmenu the screen bugs out and goes black? i have tried using the same function with $menu1 and $menu2 i have also tried seperate functions and still no difference ?

**Comment by Muqsit** [comment]
The issue has been happening ever since mojang attempted to fix their inventory crashes a few versions ago. Download [InvCrashFix](https://github.com/Muqsit/InvCrashFix) plugin, it should fix it for most cases.
Related to: https://github.com/Muqsit/InvMenu/issues/156
