### ISSUE TITLE
Menus do not open

### ISSUE THREAD

**Issue by xSuperr** [Muqsit/InvMenu#167]
When I send a player an InvMenu they do not receive it, but upon opening their inventory and closing it the menu appears. I have also consoled other developers and they have had this same issue. I can provide code snippets if required.

**Comment by Muqsit** [comment]
Yeah a code snippet and a video would be nice.

**Comment by xSuperr** [comment]
Command:
```php
        SkyblockPlayer::get($sender->getUniqueId(), function (?array $data) use ($sender, $args): void {
            if ($data === null) return;

            if ($data['island'] !== null) {
                $sender->sendMessage('§r§cYou are already in an island!');
                return;
            }

            $name = $args['name'] ?? null;

            (new IslandCreateMenu($sender, $this->plugin, $name))->display();
        });
 ```       
 
 Menu:
  ```php
     public function display(): void
    {
        $manager = InvMenuHandler::getPlayerManager();
        if ($manager->get($this->player) === null) return;
        $oldMenu = $manager->get($this->player)->getCurrent();
        if ($oldMenu !== null) {
            $this->onClose($this->player);
            self::$awaitingClose[$this->player->getName()] = $this;
        } else {
            $this->send($this->player);
        }
    }
  ```   
  
[Video](https://www.youtube.com/watch?v=L8Wup-QC6Ss)

**Comment by Muqsit** [comment]
There's a lot happening in that display() method, I'm not sure if I can directly attribute this to InvMenu without understanding what all of that's for.
I'd suggest further debugging the issue on your end.

**Comment by xSuperr** [comment]
I have two potential causes:
A. Light blocks, I replaced all air blocks in my spawn with light blocks, a block similar to barriers but that wouldn't make any sense because it was the same issue while in an area without light blocks.
B. WaterdogPE, I will test the InvMenu without waterdog in a minute 

Edit: can confirm it is not waterdog

**Comment by Muqsit** [comment]
A minimal reproduction test case would be better for both of us.
From what I understood, sending a menu doesn't work until the player opens their inventory, correct?
Does the following code work?
```php
InvMenu::create(InvMenu::TYPE_CHEST)->send($player);
```

**Comment by xSuperr** [comment]
Yeah that works without issue, it is most likely a problem on my part. Sorry about the trouble.

**Comment by reyyan987** [comment]
> [Video](https://www.youtube.com/watch?v=L8Wup-QC6Ss)

Your skyblock plugin looks amazing is it private
