### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by creeperplayer20** [Muqsit/InvMenu#168]
Hello, I'm trying to add multiple functions to items in my (test) menu, but it's doing this weird thing:

**Code**:

>             $menu->setListener(function(InvMenuTransaction $transaction) : InvMenuTransactionResult{
> 
>                 $player = $transaction->getPlayer();
>                 $transaction->getPlayer()->removeCurrentWindow();
> 
>                 if($transaction->getItemClicked()->getId() === 266){
> 
>                     $this->testForm($player);                       
>                 
>                 }
> 
>                 if($transaction->getItemClicked()->getId() === 280){
> 
>                     $this->bruhForm($player);        
>                 
>                 } return $transaction->discard()->then(function(Player $player) : void{});
>             });
> 
>             $menu->send($sender);

https://user-images.githubusercontent.com/42560781/158465799-e36ea0a6-9a8c-44b8-b2b1-0f4db1f720c6.mp4

**Comment by Muqsit** [comment]
You must send forms in then():
```php
return $transaction->discard()->then(function(Player $player) : void{
    $this->bruhForm($player);
});
```

That bug however is an issue with the game (download [InvCrashFix](https://github.com/Muqsit/InvCrashFix))
