### ISSUE TITLE
Rare bug with InvMenu in Trashcan plugin

### ISSUE THREAD

**Issue by MrBlasyMSK** [Muqsit/InvMenu#169]
I come from this [issue](https://github.com/brokiem/Trashcan/issues/1) Trashcan plugin, brokiem told me that this was a bug in InvMenu, here is the video: https://streamable.com/sbbmu2

No + plugins
PHP: 8.0.16
Pocketmine: 4.2.4
OS: linux

**Comment by Muqsit** [comment]
Yeah this has been a client bug for a while, you can install [InvCrashFix](https://github.com/Muqsit/InvCrashFix) plugin on your server to fix this.
