### ISSUE TITLE
Error While Enabling

### ISSUE THREAD

**Issue by LoveZero29** [Muqsit/InvMenu#170]
Hello Sir I am Getting Error 
I hope you can help me 
![Screenshot_2022-04-12-18-08-50-97_3686cb59f45a8f4a2b1e8d6e99664d6d](https://user-images.githubusercontent.com/90174931/162961937-ff8b7ca9-3a6b-4af0-93ee-cd9b904362c3.jpg)

**Comment by Muqsit** [comment]
That error isn't caused by InvMenu

**Comment by Muqsit** [comment]
Follow: https://github.com/Muqsit/InvMenu/wiki/Using-InvMenu-in-a-plugin#in-a-development-environment
