### ISSUE TITLE
I get this issue when trying to install this plugin 

### ISSUE THREAD

**Issue by Croc3ll** [Muqsit/InvMenu#18]
Cannot load virion InvMenu: Server has incompatible API version 3.0.0-ALPHA12

I've updated the api for both invmenu and virion to 3.0.0-ALPHA12 and still get this error

**Comment by Muqsit** [comment]
InvMenu isn't a plugin, it's a library for plugins.

**Comment by Croc3ll** [comment]
Well that doesn't really help me for the issue that i'm getting "Server has incompatible API version 3.0.0-ALPHA12" for Invmenu and with the other one of player vaults I get a signature error  is there anyway to fix the two issues i'm having with it?

**Comment by Muqsit** [comment]
Oh, you mean you are on ALPHA12? InvMenu currently works on ALPHA11 only. I'll update it in some time

**Comment by Muqsit** [comment]
https://github.com/Muqsit/InvMenu/commit/802cc3184594330994523ca127033df6aadf1207
