### ISSUE TITLE
How to add item and use it to do anything like open ui or another window

### ISSUE THREAD

**Issue by LoveZero29** [Muqsit/InvMenu#182]
I don't get How to add items because all ways are not working and how can i use them to open another window or ui

**Comment by Muqsit** [comment]
To add items, access the menu's inventory. From there, the procedure is similar to how you'd add items to player's inventories.
```php
$menu = InvMenu::create(InvMenu::TYPE_CHEST);

$inventory = $menu->getInventory();
$inventory->addItem(VanillaItems::APPLE());
$inventory->setItem(4, VanillaItems::SUGAR());

$menu->send($player);
```

To run code when a player clicks an item in a menu's inventory, set a listener to the menu.
Then you'd be able to open another menu when a player clicks an item.
See "Recursive GUI inventories!" in examples (https://github.com/Muqsit/InvMenu/wiki/Examples---InvMenu-v4#recursive-gui-inventories)

**Comment by LoveZero29** [comment]
> To add items, access the menu's inventory. From there, the procedure is similar to how you'd add items to player's inventories.
> 
> ```
> $menu = InvMenu::create(InvMenu::TYPE_CHEST);
> 
> $inventory = $menu->getInventory();
> $inventory->addItem(VanillaItems::APPLE());
> $inventory->setItem(4, VanillaItems::SUGAR());
> 
> $menu->send($player);
> ```
> 
> To run code when a player clicks an item in a menu's inventory, set a listener to the menu. Then you'd be able to open another menu when a player clicks an item. See "Recursive GUI inventories!" in examples (https://github.com/Muqsit/InvMenu/wiki/Examples---InvMenu-v4#recursive-gui-inventories)

**Comment by LoveZero29** [comment]
Sir That is getting me a error
![Screenshot_2022-04-13-13-35-13-55_3686cb59f45a8f4a2b1e8d6e99664d6d](https://user-images.githubusercontent.com/90174931/163127300-32009652-b27b-4beb-8005-48186ffa6971.jpg)

**Comment by Muqsit** [comment]
@LoveZero29 That error message isn't related to InvMenu. Add a `use pocketmine\item\VanillaItems;` line before class definition to fix it.
PocketMine discord's #plugin-dev channel would be a better place to discuss such issues.

**Comment by LoveZero29** [comment]
So sir how can i add custom name in item and set Listener in That

**Comment by Muqsit** [comment]
@LoveZero29 Since your questions is more related to PocketMine in general, join PocketMine discord's #plugin-dev channel to discuss this further.

**Comment by LoveZero29** [comment]
Umm sir i want to use Id Meta and count not by Name can you give me example so i can see

**Comment by LoveZero29** [comment]
Umm sir how can i add items by id meta not by name
