### ISSUE TITLE
Issues when changing data on Wi-Fi

### ISSUE THREAD

**Issue by cherrychip8293** [Muqsit/InvMenu#184]
There is currently an issue that can remove items from the GUI when changing from Wi-Fi to data

**Comment by Muqsit** [comment]
Send a sample code that reproduces the issue.
In case, if you have code that makes an assumption that `$menu->send($player);` instantaneously sends the menu to the player, supply a callback to the method to validate the case instead.

**Comment by cherrychip8293** [comment]
![code](https://i.imgur.com/kSDomE9.jpg)

**Comment by Muqsit** [comment]
@vkamz597 you should never be using `$menu->onClose()`, replace it with `$player->removeCurrentWindow();` instead.
