### ISSUE TITLE
Error Typed Static Property

### ISSUE THREAD

**Issue by DranxX** [Muqsit/InvMenu#186]
Error: Typed static property lmuqsit\invmenu\InvMenuHandler::$type_registry must not be accessed before initialization

**Comment by Muqsit** [comment]
Register `InvMenuHandler` soon as the plugin enables, before your plugin accesses `InvMenuHandler::getTypeRegistry()`.
https://github.com/Muqsit/InvMenu/wiki/InvMenu-v4.0-API-Documentation#initialization
