### ISSUE TITLE
Docs outdated

### ISSUE THREAD

**Issue by boi1216** [Muqsit/InvMenu#189]
The documentation for registering custom inventories is outdated.

**Comment by Muqsit** [comment]
Which documentation are you referring to?

**Comment by boi1216** [comment]
The "Registering a custom InvMenu type" part in README

**Comment by Muqsit** [comment]
Updated in [a884349](https://github.com/Muqsit/InvMenu/commit/a884349c031f3ce4edb11942ece0f8c8dca262dd)

**Comment by AIPTU** [comment]
also https://github.com/Muqsit/InvMenu#creating-an-invmenu-instance
`Item::get` is outdated
