### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Wengareki** [Muqsit/InvMenu#192]
THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: InvSee

Error: Call to undefined method pocketmine\network\mcpe\InventoryManager::getWindow()
File: plugins/InvSee.phar/src/BlockHorizons/InvSee/libs/muqsit/invmenu/session/network/PlayerNetwork
Line: 165
Type: Error
Backtrace:
#0 plugins/InvSee.phar/src/BlockHorizons/InvSee/libs/muqsit/invmenu/InvMenuEventHandler(64): BlockHorizons\InvSee\libs\muqsit\invmenu\session\network\PlayerNetwork->translateContainerOpen(object BlockHorizons\InvSee\libs\muqsit\invmenu\session\PlayerSession#954790, object pocketmine\network\mcpe\protocol\ContainerOpenPacket#981248)
#1 pmsrc/src/event/RegisteredListener(60): BlockHorizons\InvSee\libs\muqsit\invmenu\InvMenuEventHandler->onDataPacketSend(object pocketmine\event\server\DataPacketSendEvent#981249)
#2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#981249)
#3 pmsrc/src/network/mcpe/NetworkSession(436): pocketmine\event\Event->call()
#4 pmsrc/src/network/mcpe/InventoryManager(258): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\ContainerOpenPacket#981248)
#5 pmsrc/src/network/mcpe/InventoryManager(225): pocketmine\network\mcpe\InventoryManager->pocketmine\network\mcpe\{closure}()
#6 pmsrc/src/network/mcpe/InventoryManager(265): pocketmine\network\mcpe\InventoryManager->openWindowDeferred(object Closure#977326)
#7 pmsrc/src/player/Player(2531): pocketmine\network\mcpe\InventoryManager->onCurrentWindowChange(object muqsit\invmenu\inventory\InvMenuInventory#977591)
#8 /home/container/virions/InvMenu_pr-41.phar/src/muqsit/invmenu/type/graphic/BlockActorInvMenuGraphic(56): pocketmine\player\Player->setCurrentWindow(object muqsit\invmenu\inventory\InvMenuInventory#977591)
#9 /home/container/virions/InvMenu_pr-41.phar/src/muqsit/invmenu/type/graphic/MultiBlockInvMenuGraphic(38): muqsit\invmenu\type\graphic\BlockActorInvMenuGraphic->sendInventory(object Stats\player\MagicPlayer#954792, object muqsit\invmenu\inventory\InvMenuInventory#977591)
#10 /home/container/virions/InvMenu_pr-41.phar/src/muqsit/invmenu/session/PlayerSession(57): muqsit\invmenu\type\graphic\MultiBlockInvMenuGraphic->sendInventory(object Stats\player\MagicPlayer#954792, object muqsit\invmenu\inventory\InvMenuInventory#977591)
#11 /home/container/virions/InvMenu_pr-41.phar/src/muqsit/invmenu/session/network/PlayerNetwork(136): muqsit\invmenu\session\PlayerSession->muqsit\invmenu\session\{closure}(true)
#12 /home/container/virions/InvMenu_pr-41.phar/src/muqsit/invmenu/session/network/PlayerNetwork(163): muqsit\invmenu\session\network\PlayerNetwork->muqsit\invmenu\session\network\{closure}(true)
#13 /home/container/virions/InvMenu_pr-41.phar/src/muqsit/invmenu/session/network/PlayerNetwork(175): muqsit\invmenu\session\network\PlayerNetwork->processCurrent(true)
#14 /home/container/virions/InvMenu_pr-41.phar/src/muqsit/invmenu/InvMenuEventHandler(31): muqsit\invmenu\session\network\PlayerNetwork->notify(int 433984426000)
#15 pmsrc/src/event/RegisteredListener(60): muqsit\invmenu\InvMenuEventHandler->onDataPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent#977031)
#16 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent#977031)
#17 pmsrc/src/network/mcpe/NetworkSessio

**Comment by Muqsit** [comment]
> #0 plugins/InvSee.phar/src/BlockHorizons/InvSee/libs/muqsit/invmenu/InvMenuEventHandler(64): BlockHorizons\InvSee\libs\muqsit\invmenu\session\network\PlayerNetwork->translateContainerOpen(object BlockHorizons\InvSee\libs\muqsit\invmenu\session\PlayerSession#954790, object pocketmine\network\mcpe\protocol\ContainerOpenPacket#981248)

Update the plugin's version (this was addressed in [InvSee_dev-79.phar](https://poggit.pmmp.io/r/197314/InvSee_dev-79.phar)).
