### ISSUE TITLE
Crash on inv open due to protocol changes.

### ISSUE THREAD

**Issue by J1b1x** [Muqsit/InvMenu#193]
When you open your inventory, the server crashes since the last PocketMine-MP update removed the getWindow function.
Here's the error:
Error: "Call to undefined method pocketmine\network\mcpe\InventoryManager::getWindow()" (EXCEPTION) in "muqsit/invmenu/session/network/PlayerNetwork" at line 140

**Comment by Muqsit** [comment]
InvMenu is up to date with the latest stable PocketMine release. Plugins must update their InvMenu version to v4.4.1 to support later PocketMine releases (duplicate of #191).
