### ISSUE TITLE
Error InvMenu 4.4.1

### ISSUE THREAD

**Issue by ClickedTran** [Muqsit/InvMenu#196]
why is my system showing "libs\muqsit\invmenu\InvMenuHandler" not found
Help me fixed, please :<
[https://drive.google.com/file/d/1IiXNFYohxkeZEJRbuDbCCaPxnh-gZdVa/view?usp=drivesdk](url)

**Comment by Muqsit** [comment]
The error indicates that the plugin was not properly injected with InvMenu.
Refer to [**Wiki > Quick Start > Using InvMenu in a plugin**](https://github.com/Muqsit/InvMenu/wiki/Using-InvMenu-in-a-plugin).

**Comment by ClickedTran** [comment]
i tried your way, but still showing the same error, also i run the plugin on android so i can't use that syntax, is there any other way??

**Comment by Muqsit** [comment]
Can you write down the steps you tried? I'm not sure what you mean by that.

**Comment by ClickedTran** [comment]
1. I'm download InvMenu_dev-179 and DEVirion in pocketmine
2. I turn on the server so there is a folder virions
3. I paste InvMenu_dev-179.phar go to the folder virion
4. I paste the plugin that I have coded into the plugins folder of pocketmine
5. I turn on the server and get error like picture

I have tried everything like pasting InvMenu_dev-179.phar into the plugins folder but it still doesn't work

**Comment by Muqsit** [comment]
> 1. I'm download InvMenu_dev-179 and DEVirion in pocketmine
> 2. I turn on the server so there is a folder virions
> 3. I paste InvMenu_dev-179.phar go to the folder virion
> 4. I paste the plugin that I have coded into the plugins folder of pocketmine
> 5. I turn on the server and get error like picture
> 
> I have tried everything like pasting InvMenu_dev-179.phar into the plugins folder but it still doesn't work

In a development environment (when your plugin is in folder structure instead of a `.phar`), your plugin must use the namespace without the `libs\` (i.e., `muqsit\invmenu\InvMenuHandler`).

When you export your plugin as a `.phar`, follow the steps in [**Wiki > Quick Start > Using InvMenu in a plugin > In a production environment**](https://github.com/Muqsit/InvMenu/wiki/Using-InvMenu-in-a-plugin#in-a-production-environment) to inject the virion. This will automatically prepend the `libs\` namespace.

**Comment by ClickedTran** [comment]
> > 1. I'm download InvMenu_dev-179 and DEVirion in pocketmine
> > 2. I turn on the server so there is a folder virions
> > 3. I paste InvMenu_dev-179.phar go to the folder virion
> > 4. I paste the plugin that I have coded into the plugins folder of pocketmine
> > 5. I turn on the server and get error like picture
> > 
> > I have tried everything like pasting InvMenu_dev-179.phar into the plugins folder but it still doesn't work
> 
> In a development environment (when your plugin is in folder structure instead of a `.phar`), your plugin must use the namespace without the `libs\` (i.e., `muqsit\invmenu\InvMenuHandler`).
> 
> When you export your plugin as a `.phar`, follow the steps in [**Wiki > Quick Start > Using InvMenu in a plugin > In a production environment**](https://github.com/Muqsit/InvMenu/wiki/Using-InvMenu-in-a-plugin#in-a-production-environment) to inject the virion. This will automatically prepend the `libs\` namespace.

Well, I have to move the file outside the `src/` directory for it to work, but thanks you supported for me :3
Love <3

**Comment by Muqsit** [comment]
While it may be a common practice to move virions into a `libs/` folder within a plugin and use a namespace with `libs/` prepended, this is not the correct method for including virions in a plugin. Instead, the instructions provided in https://poggit.github.io/support/virion.html should be followed (the InvMenu wiki contains a watered-down version of this). It is generally best not to move virion source folders to any other location.
