### ISSUE TITLE
PM5 Version

### ISSUE THREAD

**Issue by xS91D** [Muqsit/InvMenu#199]
PM5 Version

**Comment by Muqsit** [comment]
InvMenu v4.6.1 exclusively supports PM5. You may use [InvMenu_dev-184.phar](https://poggit.pmmp.io/r/208364/InvMenu_dev-184.phar) in your PM5 plugin and make the following changes to your `poggit.yml`:
```diff
projects:
  MyPluginName:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
-       branch: "4.0"
-       version: ^4.5.1
+       branch: pm5
+       version: ^4.6.1
```
