### ISSUE TITLE
Incorrect inventory sent when replacing an existing chest | PMMP 4.18

### ISSUE THREAD

**Issue by Nat392** [Muqsit/InvMenu#207]
Hello, I have a bug with your code and PMMP v.4.18

https://user-images.githubusercontent.com/54687432/228914726-94e46504-a046-4a01-8e02-15c64df5e9fa.mov

https://user-images.githubusercontent.com/54687432/228914734-0de56063-e866-4031-962f-8790da2ab707.mov

**Comment by Muqsit** [comment]
Hi, can you explain what the bug is and what the video demonstrates?

**Comment by Nat392** [comment]
When you try to open a GUI, if a chest is nearby, the interface that opens is "bug". The video shows a player trying to open a GUI by tapping on a minion, he gets a double empty chest, but by pressing the slots, the real interface appears.

**Comment by Nat392** [comment]
![image](https://user-images.githubusercontent.com/54687432/229127651-aa5f7d49-c16d-418d-a42c-5f9526141b8b.png)

Or a member who opens an enderchest with the command /ec, and the open interface is a double chest.

**Comment by Nat392** [comment]
Look the video

https://user-images.githubusercontent.com/54687432/229133344-2b19a086-81e7-464d-a18f-bd566519b919.mp4

**Comment by Nat392** [comment]
Hello @Muqsit , any news ?

**Comment by Muqsit** [comment]
I have been able to reproduce this bug on my end, but due to time constraints I am unable to work on a nice way to address it.
A simple workaround to this bug is to set the block left and right of the chest to air while the player has the chest open. This can be done by overriding `InvMenu::TYPE_CHEST` during plugin enable:
```diff
protected function onEnable() : void{
	if(!InvMenuHandler::isRegistered()){
		InvMenuHandler::register($this);
	}

+	$registry = InvMenuHandler::getTypeRegistry();
+	$registry->register(InvMenu::TYPE_CHEST, new class($registry->get(InvMenu::TYPE_CHEST)) implements InvMenuType{
+		public function __construct(
+			private InvMenuType $inner
+		){}

+		public function createGraphic(InvMenu $menu, Player $player) : ?InvMenuGraphic{
+			$parent = $this->inner->createGraphic($menu, $player);
+			if(!($parent instanceof PositionedInvMenuGraphic)){
+				return null;
+			}

+			// Workaround for https://github.com/Muqsit/InvMenu/issues/207
+			// Set block at east and west of InvMenu::TYPE_CHEST to air.
+			$pos = $parent->getPosition();
+			return new MultiBlockInvMenuGraphic([
+				$parent,
+				new BlockInvMenuGraphic(VanillaBlocks::AIR(), $pos->east(), null, 0),
+				new BlockInvMenuGraphic(VanillaBlocks::AIR(), $pos->west(), null, 0)
+			]);
+		}

+		public function createInventory() : Inventory{
+			return $this->inner->createInventory();
+		}
+	});
}
```

An example script plugin using this workaround is listed here: https://gist.github.com/Muqsit/18400e53b132d166f13189e7f316658e

**Comment by Nat392** [comment]
I tried this workaround but it didn't work, the bug still occurs.

**Comment by Jack10270** [comment]
The workaround fixes it but my suggestion is this method:- if a block already exists find another spot to set the block
