### ISSUE TITLE
Using a custom inventory with InvMenu causes server to hang

### ISSUE THREAD

**Issue by SenseiTarzan** [Muqsit/InvMenu#214]
I use the pm5 version.
This is due to the InvMenu, because if I quickly click several times on a block that has an invMenu, my server freezes like hell.

**Comment by SenseiTarzan** [comment]
![image](https://github.com/Muqsit/InvMenu/assets/32621158/092429ab-38a7-4a70-bad6-da19a99a84d2)

**Comment by SenseiTarzan** [comment]
https://timings.pmmp.io/?id=306717

**Comment by SenseiTarzan** [comment]
Event.php
```php
    private array $waiting = [];
    #[EventAttribute(EventPriority::LOWEST)]
    public function onInteract(PlayerInteractEvent $event)
    {
        $player = $event->getPlayer();
        $block = $event->getBlock();
        $action = $event->getAction();

        if ($action === PlayerInteractEvent::RIGHT_CLICK_BLOCK) {
            if ($block->getTypeId() === BlockTypeIds::ENDER_CHEST) {
                $event->cancel();
                if (isset($this->waiting[$player->getName()]) && $this->waiting[$player->getName()] > hrtime(true)) return;
                $this->waiting[$player->getName()] = hrtime(true) + 3e9;
                $inventory = InvMenu::create( "invmenu:ender_chest", $player->getEnderInventory());
                $size = SlotEnum::getSlotEnumByPermissions($player);
                $inventory->setName( $size->getPrefix(). "EnderChest");
                $inventory->setInventoryCloseListener(function (Player $player, Inventory $inventory) use($size) {
                    $player->getEnderInventory()->setContents(array_slice($inventory->getContents(), 0, $size->getSlot()));
                });
                $inventory->send($player);
            }
        }
    }
```
Main.php
```php
  protected function onEnable(): void
    {
        EventLoader::loadEventWithClass($this, InventoryListener::class);
        InvMenuHandler::register($this);
        InvMenuHandler::getTypeRegistry()->register("invmenu:ender_chest", InvMenuTypeBuilders::BLOCK_ACTOR_FIXED()
            ->setBlock(VanillaBlocks::ENDER_CHEST())
            ->setSize(27)
            ->setBlockActorId("EnderChest")
            ->build());
    }
```

**Comment by SenseiTarzan** [comment]
even with the waiting I can do it if I spam the block at least 3 times

**Comment by SenseiTarzan** [comment]
![image](https://github.com/Muqsit/InvMenu/assets/32621158/ba6479c7-e4bf-4d33-872e-93a6bc4b8a56)

**Comment by SenseiTarzan** [comment]
if we spam the InvMenu opening and the one that freezes comes from the menu onClose
![image](https://github.com/Muqsit/InvMenu/assets/32621158/2ae47d87-2c74-49f5-9b98-6a23a4087c0f)
*

**Comment by SenseiTarzan** [comment]
i found the compable
![image](https://github.com/Muqsit/InvMenu/assets/32621158/704f5555-8a06-4cf4-9fb8-ee53ecb1fcdd)

when it synchronizes the inventorycustom even if it closes without changing anything and creates performance problems

**Comment by SenseiTarzan** [comment]
it would be best to use the custom inventory as the main inventory

**Comment by SenseiTarzan** [comment]
even if it's not advisable

**Comment by Muqsit** [comment]
This issue stems from dangling `InventoryListener` instances stacking up in the custom inventory with every call to `InvMenu::create()`. The solution is to call `$menu->setInventory(null);` once the menu is no longer accessible or in use.
```php
$menu = InvMenu::create( "invmenu:ender_chest", $player->getEnderInventory());
$menu->setName( "EnderChest");
$menu->send($player, null, function(bool $success) use($menu) : void{
	if($success){
		$menu->setInventoryCloseListener(function(Player $player, Inventory $inventory) use($menu) : void{
			$player->getEnderInventory()->setContents(array_slice($inventory->getContents(), 0, 27));
			$menu->setInventory(null);
			$menu->setInventoryCloseListener(null);
		});
	}else{
		$menu->setInventory(null);
	}
});
```
I generally would instruct against the use of custom inventory feature in InvMenu. Plugins can reimplement the inventory synchronization feature themselves and do better at collecting memory garbage (this is similar to what was done in [BlockHorizons/InvSee](https://github.com/BlockHorizons/InvSee)).

On a side note, the inventory close listener is not necessary in your case. InvMenu will keep its inventory synchronized with the custom inventory.

**Comment by SenseiTarzan** [comment]
OK, thanks a lot

**Comment by SenseiTarzan** [comment]
You should put that on the wiki

**Comment by Muqsit** [comment]
Yeah, I'll make a note of this on the wiki 👍
