### ISSUE TITLE
Nathing Work!

### ISSUE THREAD

**Issue by GabBiswajit** [Muqsit/InvMenu#220]
Invmenu Don't Work Gui Don't Open 👐 On 1.20.10 !

Muqsit Buddy Fix It Fast It's A Important Plugin For My Server !

**Comment by Muqsit** [comment]
This has already been addressed in https://github.com/Muqsit/InvMenu/commit/c597754737efad699592ad4b9c8f63462328fe86. Plugins depending on InvMenu much update to v4.6.3 (pm5) or the corresponding pm4 version.
