### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by scamaccas** [Muqsit/InvMenu#226]
TypeError: "muqsit\invmenu\InvMenu::handleInventoryTransaction(): Return value must be of type muqsit\invmenu\transaction\InvMenuTransactionResult, null returned" (EXCEPTION) in "/root/virions/InvMenu-pm5/src/muqsit/invmenu/InvMenu" at line 176

**Comment by Muqsit** [comment]
Can you provide backtrace and the listener you are setting?
