### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gamegam** [Muqsit/InvMenu#227]
How to display 1 as a message when an item is put in item 1 and closed?

**Comment by Muqsit** [comment]
Attach a transaction listener (using `$menu->setListener($listener);`) that listens for items being taken in and placed in the inventory.
Do you want to send message when a player clicks a specific slot?

**Comment by gamegam** [comment]
Yes
But I can't load a slot

**Comment by Muqsit** [comment]
`$transaction->getAction()->getSlot()` returns the menu inventory's slot number.
