### ISSUE TITLE
Pm5 Change 

### ISSUE THREAD

**Issue by GabBiswajit** [Muqsit/InvMenu#228]
What's Change For This In Pm5?
```$visitingPlayer = Server::getInstance()->getPlayerExact(str_replace(["§r §b", " §r"], ["", ""], $itemOut->getCustomName()));```
```$inv->setItem(21, ItemFactory::getInstance()->get(0, 0, 0));```

**Comment by Muqsit** [comment]
The code doesn't seem to interact with InvMenu's API, but `ItemFactory::getInstance()->get(0, 0, 0)` must be replaced with `VanillaItems::AIR()`. Alternatively, you can use a simpler `$inv->clear(21);`.

**Comment by GabBiswajit** [comment]
@Muqsit what is use ```if($itemOutId === 262 && $itemOutMeta === 0)
        {
          $this->MainGUI($player);
        }``` In Pm5 This Is Not Work..

```$inv->setItem(48, GlobalItemDataHandlers::getDeserializer()->deserializeStack(GlobalItemDataHandlers::getUpgrader()->upgradeItemTypeDataInt(262, 0, 1, null))->setCustomName("§r §cBack §r\n§r §7click to go back to the privious menu §r"));``` 
I Use This

**Comment by Muqsit** [comment]
What is the functionality you're trying to achieve?

**Comment by GabBiswajit** [comment]
It's send player to MainGUI When Player Click On Item 262.

**Comment by GabBiswajit** [comment]
```$inv->setItem(48, VanillaBlocks::STONE()->setCustomName("§r §cBack §r\n§r §7click to go back to the privious menu §r"));```

NOW CAN YOU TELL ME HOW I DO THIS WHEN PLAYER CLICK ON STONE THAN SEND THE PLAYER TO MainGUI ??
@Muqsit

**Comment by GabBiswajit** [comment]
@Muqsit reply

**Comment by Muqsit** [comment]
Item ID and meta were removed in PM5. Use `Item::getTypeId()` instead for comparison:
```php
if($item->getTypeId() === ItemTypeIds::fromBlockTypeId(VanillaBlocks::STONE()->getTypeId())){
	// send player to main gui
}
```
I'd suggest familiarizing with PocketMine API 5 changes that were officially documented. It includes a broader range of changes: https://github.com/pmmp/PocketMine-MP/blob/stable/changelogs/5.0.md#pocketmineitem

Alternatively, if the 'back button' is always present in slot 48, you can simply check for slot instead: `if($transaction->getAction()->getSlot() === 48){ ... }`.

**Comment by GabBiswajit** [comment]
What Is Visible For```$item``` ??

**Comment by GabBiswajit** [comment]
@Muqsit

**Comment by Muqsit** [comment]
What do you mean by Visible?

**Comment by GabBiswajit** [comment]
@Muqsit variable*
```Undefined variable $item```

**Comment by Muqsit** [comment]
$item would be $transaction->getItemClicked() for your case.

**Comment by GabBiswajit** [comment]
Ok

**Comment by GabBiswajit** [comment]
@Muqsit It's Work ??

`if($item->getTypeId() === ItemTypeIds::fromBlockTypeId(VanillaItems::AIR()->getTypeId()))
        {
          $member = str_replace(["§r §e", " §r"], ["", ""], $itemOutName);
          $this->Management($player, $member);
        }`

`$inv->setItem(20, VanillaItems::AIR());`

`$inv->setItem(21, VanillaItems::AIR());`

**Comment by GabBiswajit** [comment]
@Muqsit reply

**Comment by Muqsit** [comment]
I unfortunately cannot help further without knowing the intricate details of your goal. You'll have to work on that by yourself. Look around the wiki for further documentation and examples:
- [InvMenu v4.0 Documentation](https://github.com/Muqsit/InvMenu/wiki/InvMenu-v4.0-API-Documentation)
- [InvMenu v4.0 Examples](https://github.com/Muqsit/InvMenu/wiki/Examples---InvMenu-v4)
- [Plugins that use InvMenu](https://github.com/Muqsit/InvMenu/wiki/List-of-plugins-using-InvMenu)
