### ISSUE TITLE
How can we add vanilla blocks in menu?

### ISSUE THREAD

**Issue by ItsSachan** [Muqsit/InvMenu#229]
How can I do so?

**Comment by Muqsit** [comment]
The same way you'd add items to any other PocketMine inventory, use `$menu->getInventory()->addItem($item)`. For blocks, you'd be converting them to their item equivalent by calling `Block::asItem()`.
```php
$item = VanillaBlocks::STONE()->asItem();
$menu->getInventory()->addItem($item);
```

**Comment by ItsSachan** [comment]
Tysm
