### ISSUE TITLE
Is is possible to add custom items?

### ISSUE THREAD

**Issue by ItsSachan** [Muqsit/InvMenu#230]
I made some custom food and blocks is it possible is add then in menu/
if possible how can i do so?

**Comment by Muqsit** [comment]
If the custom items can be obtainable in-game, yes they can be added to the menu.

**Comment by ItsSachan** [comment]
> If the custom items can be obtainable in-game, yes they can be added to the menu.

i added a item named as GodPot id 1000 how can i add it

**Comment by Muqsit** [comment]
> > If the custom items can be obtainable in-game, yes they can be added to the menu.
> 
> i added a item named as GodPot id 1000 how can i add it

Are you able to obtain the item ingame?

**Comment by ItsSachan** [comment]
> > > If the custom items can be obtainable in-game, yes they can be added to the menu.
> > 
> > 
> > i added a item named as GodPot id 1000 how can i add it
> 
> Are you able to obtain the item ingame?

yep

**Comment by ItsSachan** [comment]
Pls reply I am able to obtain custom item in game

**Comment by Muqsit** [comment]
This largely depends on how you implemented the items.
If you're following what https://github.com/pmmp/RegisterBlocksDemoPM5 demonstrates, you can obtain an `Item` instance by calling `ExtraVanillaItems::...()`:
```php
$item = ExtraVanillaItems::IRON_HORSE_ARMOR();
$menu->getInventory()->addItem($item);
```

If you're using Customies, there is a wiki section on how to register and obtain custom items: https://github.com/CustomiesDevs/Customies/wiki/Custom-Items.

These are the only two kinds of ways of registering items that I am aware of, and probably also the only available reliable means in contrast with other custom methods. If you are using a different method, ask the developer on how an `Item` instance for an item with a custom ID can be obtained.
