### ISSUE TITLE
Is it possible to add custom texture in invmenu?

### ISSUE THREAD

**Issue by ItsSachan** [Muqsit/InvMenu#231]
I wana add some customer images so I wana know

**Comment by Muqsit** [comment]
Custom images are defined by resource packs. Once you have defined a custom UI, you may register an entity-backed InvMenu (if the UI is an entity inventory), or a block-backed InvMenu (if the UI is a block inventory). Generally, resource packs tend to differentiate between UIs based on keywords in the inventory's title.
- [Examples on registering block-backed InvMenu types](https://github.com/Muqsit/InvMenu/blob/pm5/src/muqsit/invmenu/type/InvMenuTypeRegistry.php#L20-L39)
- [Example plugin registering an entity-backed InvMenu](https://github.com/Muqsit/CustomSizedInvMenu)

**Comment by ItsSachan** [comment]
> Custom images are defined by resource packs. Once you have defined a custom UI, you may register an entity-backed InvMenu (if the UI is an entity inventory), or a block-backed InvMenu (if the UI is a block inventory). Generally, resource packs tend to differentiate between UIs based on keywords in the inventory's title.
> 
> * [Examples on registering block-backed InvMenu types](https://github.com/Muqsit/InvMenu/blob/pm5/src/muqsit/invmenu/type/InvMenuTypeRegistry.php#L20-L39)
> * [Example plugin registering an entity-backed InvMenu](https://github.com/Muqsit/CustomSizedInvMenu)

there are some youtuber who are able to change background of gui menu how can i do that

**Comment by Muqsit** [comment]
> > Custom images are defined by resource packs. Once you have defined a custom UI, you may register an entity-backed InvMenu (if the UI is an entity inventory), or a block-backed InvMenu (if the UI is a block inventory). Generally, resource packs tend to differentiate between UIs based on keywords in the inventory's title.
> > 
> > * [Examples on registering block-backed InvMenu types](https://github.com/Muqsit/InvMenu/blob/pm5/src/muqsit/invmenu/type/InvMenuTypeRegistry.php#L20-L39)
> > * [Example plugin registering an entity-backed InvMenu](https://github.com/Muqsit/CustomSizedInvMenu)
> 
> there are some youtuber who are able to change background of gui menu how can i do that

You can design and implement one through a resource pack.

**Comment by ItsSachan** [comment]
> > > Custom images are defined by resource packs. Once you have defined a custom UI, you may register an entity-backed InvMenu (if the UI is an entity inventory), or a block-backed InvMenu (if the UI is a block inventory). Generally, resource packs tend to differentiate between UIs based on keywords in the inventory's title.
> > > 
> > > * [Examples on registering block-backed InvMenu types](https://github.com/Muqsit/InvMenu/blob/pm5/src/muqsit/invmenu/type/InvMenuTypeRegistry.php#L20-L39)
> > > * [Example plugin registering an entity-backed InvMenu](https://github.com/Muqsit/CustomSizedInvMenu)
> > 
> > 
> > there are some youtuber who are able to change background of gui menu how can i do that
> 
> You can design and implement one through a resource pack.

ANY EXAMPLE

**Comment by Muqsit** [comment]
I do not have any expertise in designing custom UIs through resource packs, so no. If you have a UI resource pack, I can write a public example plugin on how to wire it with InvMenu.

**Comment by ItsSachan** [comment]
> I do not have any expertise in designing custom UIs through resource packs, so no. If you have a UI resource pack, I can write a public example plugin on how to wire it with InvMenu.

ok i will manage resource pack but pls make a public example
