### ISSUE TITLE
Inventory sending

### ISSUE THREAD

**Issue by ItsSachan** [Muqsit/InvMenu#232]
How can we send same inventory to different player but the inside content that first user saved can only be seen by him if other open he sees his placed items

**Comment by Muqsit** [comment]
Use a listener to handle transactions occurring within the menu.
```php
$menu->setListener(function(InvMenuTransaction $transaction) : InvMenuTransactionResult{
	$player = $transaction->getPlayer();
	if(/* $player is not allowed */){
		return $transaction->discard();
	}
	return $transaction->continue();
});
```

**Comment by ItsSachan** [comment]
> 

It is not working 
https://github.com/inxomnyaa/Backpack/tree/master like this when we interact with different it opens different inventory but the whole code is same

**Comment by Muqsit** [comment]
Can you clarify what's not working exactly?

**Comment by ItsSachan** [comment]
yep it was sending same inv

**Comment by Muqsit** [comment]
Menus can be sent to multiple players, you must store the menu instance in memory to pass it around.

**Comment by ItsSachan** [comment]
> Menus can be sent to multiple players, you must store the menu instance in memory to pass it around.

You mean in that player game it should store?

**Comment by Muqsit** [comment]
Store it within the plugin temporarily, in an array. https://github.com/BlockHorizons/InvSee as an example allows permission-based control over player inventories in real-time.

**Comment by Muqsit** [comment]
If you want to send the same menu with different inventories, it is not possible. You'd need to create a different menu for each inventory. Plugins usually construct a new menu at request: https://github.com/search?q=InvMenu%3A%3Acreate+language%3APHP&type=code

If you want to send the same menu to multiple players, you may want to cache the menu somewhere in memory so you retain an instance to the menu. `InvMenu::send()` lets you send the same menu to different players.
```php
$menu = InvMenu::create(InvMenu::TYPE_CHEST);
$menu->send($player1);
$menu->send($player2);

// allow only $player1 to make changes
$menu->setListener(function(InvMenuTransaction $transaction) use($player1) : InvMenuTransactionResult{
	$player = $transaction->getPlayer();
	if($player === $player1){
		return $transaction->continue();
	}
	return $transaction->discard();
});
```

**Comment by ItsSachan** [comment]
How can we full whole gui with one line code and also add some item in particular slots

**Comment by ItsSachan** [comment]
Please reply

**Comment by Muqsit** [comment]
> How can we full whole gui with one line code and also add some item in particular slots

Why not just write a function that builds a menu?
