### ISSUE TITLE
Sending InvMenu

### ISSUE THREAD

**Issue by ItsSachan** [Muqsit/InvMenu#233]
I have two plugins 
I want the other plugin to get inv menu from another and send it to player

**Comment by Muqsit** [comment]
There aren't any set limitations against sharing menu instances across plugins

**Comment by ItsSachan** [comment]
from same plugin is possible?

**Comment by Muqsit** [comment]
Yes

**Comment by ItsSachan** [comment]
public function MainMenu(DeterministicInvMenuTransaction $transaction) {

    $player = $transaction->getPlayer();
    $action = $transaction->getAction();
    $inventory = $action->getInventory();
    $item = $transaction->getItemClicked();

    if($item->getCustomName() === "Minions"){
      $this->cobble($sender);
    }
  }
  
  It is not sending menu which is in another folder

**Comment by SwiftyMCPE** [comment]
Show the full code

**Comment by SwiftyMCPE** [comment]
Maybe you not imported that

**Comment by ItsSachan** [comment]
<?php
declare(strict_types=1);

namespace ItsSachan\RecipeGUI;

use pocketmine\player\Player;
use pocketmine\color\Color;
use Closure;

use pocketmine\plugin\PluginBase;
use pocketmine\event\Listener;
use pocketmine\event\player\PlayerInteractEvent;
use pocketmine\event\player\PlayerJoinEvent;

use pocketmine\command\Command;
use pocketmine\command\CommandSender;

use pocketmine\item\Item;
use pocketmine\item\ItemIds;
use pocketmine\item\VanillaItems;

use pocketmine\block\Block;
use pocketmine\block\BlockBreakInfo;
use pocketmine\block\BlockIdentifier;
use pocketmine\block\BlockTypeIds;
use pocketmine\block\BlockTypeInfo;
use pocketmine\block\Opaque;
use pocketmine\utils\CloningRegistryTrait;
use pocketmine\block\VanillaBlocks;

use pocketmine\nbt\tag\CompoundTag;
use pocketmine\nbt\tag\ListTag;
use pocketmine\utils\TextFormat;

use muqsit\invmenu\InvMenu;
use muqsit\invmenu\InvMenuHandler;
use muqsit\invmenu\transaction\DeterministicInvMenuTransaction;
use muqsit\invmenu\transaction\InvMenuTransaction;

use customiesdevs\customies\item\CreativeInventoryInfo;
use customiesdevs\customies\item\ItemComponentsTrait;
use customiesdevs\customies\item\CustomiesItemFactory;

use ItsSachan\RecipeGUI\Recipe\Minions\cobble;

class Main extends PluginBase implements Listener {

    public function onEnable(): void {
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
        $this->getLogger()->info("RecipeGUI by ItzSachan");

        $this->saveDefaultConfig();


        		if(!InvMenuHandler::isRegistered()){
            			InvMenuHandler::register($this);
            		}
    }

    public function onCommand(CommandSender $sender, Command $command, string $label, array $args): bool{
        switch($command->getName()){
            case "recipe":
              if($sender->hasPermission("recipe.cmd")){
                $this->recipe($sender);
              } else {
                $sender->sendMessage("You Don't Have Permission To Use This Command");
             }

        }

        return true;

  }

  public function recipe(Player $player) { 

    $menu = InvMenu::create(InvMenu::TYPE_DOUBLE_CHEST);
    $menu->setName("§l§6Fast Travel GUI");
    $menu->setListener(InvMenu::readonly(Closure::fromCallable([$this, "MainMenu"]
  
    )));
    $menu->readonly();
    $menu->getInventory()->setItem(13, VanillaBlocks::GRASS()->asItem()->setCustomName("Minions"));
    
  
    $menu->send($player);
   
   
}

public function MainMenu(DeterministicInvMenuTransaction $transaction) {

    $player = $transaction->getPlayer();
    $action = $transaction->getAction();
    $inventory = $action->getInventory();
    $item = $transaction->getItemClicked();

    if($item->getCustomName() === "Minions"){
      $this->cobble($sender);
    }
  }
}

**Comment by SwiftyMCPE** [comment]
LMAO it's not readable

**Comment by ItsSachan** [comment]
oh

**Comment by SwiftyMCPE** [comment]
Send me in discord

**Comment by ItsSachan** [comment]
ur username?

**Comment by SwiftyMCPE** [comment]
AstroAI#0060

**Comment by SwiftyMCPE** [comment]
Are u alive?

**Comment by ItsSachan** [comment]
can u help?
