### ISSUE TITLE
Dubble Chest cant open

### ISSUE THREAD

**Issue by Hyroxing-Development** [Muqsit/InvMenu#24]
18:41:27 CRITICAL > Could not pass event 'pocketmine\event\inventory\InventoryTransactionEvent' to 'LobbySystem-RevengerMC v1': Call to undefined method pocketmine\Server::getScheduler() on muqsit\invmenu\InvMenuHandler
18:41:27 CRITICAL > Error: "Call to undefined method pocketmine\Server::getScheduler()" (EXCEPTION) in "/RevengerMC/Lobby-1/virions/InvMenu-master/src/muqsit/invmenu/inventories/DoubleChestInventory" at line 53

**Comment by Muqsit** [comment]
Use dev branch

**Comment by Muqsit** [comment]
Refer https://twitter.com/muqsitrayyan/status/1006279845096148992

**Comment by Hyroxing-Development** [comment]
The Error is fixed but if I open the dubblechest the chest closed

**Comment by Muqsit** [comment]
This has been fixed, use this commit: https://github.com/Muqsit/InvMenu/commit/aff1d8eb15d79d41d6a98135e3bc555871b05983
