### ISSUE TITLE
setName()

### ISSUE THREAD

**Issue by chaosfreak93** [Muqsit/InvMenu#28]
17:47:20 CRITICAL > Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'GameTeleporter v0.0.9': Non-static method muqsit\invmenu\InvMenu::setName() should not be called statically on ChaosDev93\GameTeleporter
17:47:20 CRITICAL > ErrorException: "Non-static method muqsit\invmenu\InvMenu::setName() should not be called statically" (EXCEPTION) in "GameTeleporter - CD/src/ChaosDev93/GameTeleporter" at line 103

I am using Altay

**Comment by Muqsit** [comment]
The error should suffice.
