### ISSUE TITLE
Big issue...

### ISSUE THREAD

**Issue by BaconOFBurger** [Muqsit/InvMenu#39]
Hi could you fix this please? Kinda annoying
https://github.com/Muqsit/InvMenu/blob/master/src/muqsit/invmenu/inventories/ChestInventory.php#L37
> Tile::CHEST   const does not exist anymore in pmmp....

**Comment by Muqsit** [comment]
InvMenu currently doesn't support API 4.0.0, but there's a 4.0.0 branch still in the works.
