### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by DeadOnBushPH** [Muqsit/InvMenu#40]
Error:
ErrorException: "Undefined variable: menu" (EXCEPTION) in "plugins/ChestGui.phar/src/GUI/Main" at line 43

My Code:
<?php
namespace GUI;

use muqsit\invmenu\{InvMenu, InvMenuHandler};
use pocketmine\command\{Command, CommandSender};
use pocketmine\item\Item;
use pocketmine\nbt\BigEndianNBTStream;
use pocketmine\nbt\tag\{CompoundTag, ListTag};
use pocketmine\Player;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\{Config, TextFormat as TF};

class Main extends PluginBase{

    public function onEnable() : void{
        if(!InvMenuHandler::isRegistered()){
            InvMenuHandler::register($this);
        }

        $menu = InvMenu::create(InvMenu::TYPE_CHEST)
        ->readonly()
        ->setName("The Inventory's Name")
        ->setListener([$this, "handleMenuSelection"]);

        $inv = $menu->getInventory();
        $item = Item::get(Item::STONE);
        $item->setCustomName("Tap Me");
        $inv->setItem(0, $item);
    }

    public function handleMenuSelection(Player $player, Item $itemClicked) : bool{
        if($itemClicked->getId() === Item::STONE){
            $player->getServer()->dispatchCommand($player, "test 1");
        }
        return true;
    }

    public function onCommand(CommandSender $sender, Command $cmd, string $label, array $args) : bool {

        switch($cmd->getName()){

            case "test":
            $menu->send($sender);
            break;
        }
    }
}

**Comment by Muqsit** [comment]
Sorry but this issue tracker isn't meant for discussing generic coding issues. Usually undefined variable errors are caused because as the error states, the variable isn't defined. If you aren't the author of that plugin, report the error to the plugin author so they can solve their issue.
