### ISSUE TITLE
Issues instantly opening a new menu

### ISSUE THREAD

**Issue by thebigsmileXD** [Muqsit/InvMenu#41]
I tried to open a menu from another menu.

Following issues occurred:
From a hopper to a chest the hopper will just close, and the chest inventory will not open, since the hopper is replaced with its original block in that tick.

From a chest to another chest inventory, the tile sometimes gets stuck in the air, and the menu's title will not change.

**Comment by Muqsit** [comment]
Yeah, I've noticed this as well. I had introduced `BaseFakeInventory::setDefaultSendDelay(int $ticks)` to this problem which also simplifies the implementation of delay for double chests: https://github.com/Muqsit/InvMenu/blob/master/src/muqsit/invmenu/inventories/DoubleChestInventory.php#L32-#L41.

For now, I think the only possible workaround is to send the recurring inventory after a delay (8 ticks sounds like a good number). I'm trying to find a better solution to combat this issue as well as the issue with double chest delays. These delays still have a small chance of not working when the client is lagging.

Example of a recursive inventory impl workaround:
```php
$menu = InvMenu::create(InvMenu::TYPE_CHEST);
$menu2 = InvMenu::create(InvMeu::TYPE_HOPPER);
$menu->setListener(function(Player $player, Item $itemClicked, Item $itemClickedWith, SlotChangeAction $action) use($menu2) : bool{
    $player->removeWindow($action->getInventory());

    $menu2->getInventory($player)->setDefaultSendDelay(8);
    $menu2->send($player);
    // $meu2->setDefaultSendDelay(0); // reset menu's default send delay to 0
    return false;
});
```

**Comment by PixelzChris** [comment]
It happens to me too

**Comment by Muqsit** [comment]
This has been solved in https://github.com/Muqsit/InvMenu/commit/e4ba7e4f24806fb36a59e0ceb30d612af20a449d but note that the commit targets `4.0` branch InvMenu v3.0 which is backwards incompatible with v2.0.
