### ISSUE TITLE
DoubleChestInventories are not working

### ISSUE THREAD

**Issue by TobiasG-DE** [Muqsit/InvMenu#43]
I have made an simple DoubleChestInventory. When I try to open it with the latest version of PMMP, this happens: 
https://youtu.be/JPohWhdOul0

There is no error occuring in the console.

**Comment by Muqsit** [comment]
Can you send the code you're using to create the menu?

**Comment by TobiasG-DE** [comment]
`  $menu_items = ChestMenuAPI::getMenuItems($menu_name);
        $maxslot = 0;
        foreach (array_keys($menu_items) as $key) {
            $item = $menu_items[$key];
            if (is_array($item) and $key != 'actions') {
                if ($maxslot < $item['slot']) {
                    $maxslot = $item['slot'];
                }
            }

        }
        if ($maxslot > 26) {
            $menu = InvMenu::create(InvMenu::TYPE_DOUBLE_CHEST);
            $this->chest = InvMenu::TYPE_DOUBLE_CHEST;
        } else {
            $menu = InvMenu::create(InvMenu::TYPE_CHEST);
            $this->chest = InvMenu::TYPE_CHEST;
        }
        $menu->readonly();
        $menu->setName(TextFormat::GOLD.$menu_name);
        $inv = $menu->getInventory();
        $inv->clearAll();

        foreach (array_keys($menu_items) as $key) {
            $data = $menu_items[$key];
            if (is_array($data) and $key != 'actions') {
                $item = ItemAPI::getItem($data);
                $bool = true;
                if ($data['permissions'] != "") {
                    if (!$data['Show-Perms']) {
                        if (!$player->hasPermission($data['permissions'])) {
                            $bool = false;
                        }
                    }
                }
                if ($bool) {
                    $inv->setItem($data['slot'], $item);
                }
            }
        }

        $menu->setListener([$this, "onTransaction"]);
        $menu->setInventoryCloseListener(function(Player $player, BaseFakeInventory $inventory) : void{
            ItemAPI::setItems($player, ConfigAPI::getMainMenu(), MenuType::HOT_BAR_TYPE);
        });

        $menu->send($player);
    }
`
This is the code we are using.

**Comment by TobiasG-DE** [comment]
Fixed by latest pmmp version

**Comment by iTzFreeHD** [comment]
No it is not fixed
