### ISSUE TITLE
1.11 Chests are not opening

### ISSUE THREAD

**Issue by iTzFreeHD** [Muqsit/InvMenu#44]
Version: PocketMine-MP 3.8.0 Realese
Last InvMenu Version

Chests failed open. InvMenu spawns a chest but the Inventory doesnt open there is no Error after PMMP 1.11 Update the Chests are borken. Sry for my bad English :D

**Comment by iTzFreeHD** [comment]
btw the bug that commited by TobiasG-DE is not fixed

**Comment by Muqsit** [comment]
Please provide more information on the issue. It works flawlessly on my end.
