### ISSUE TITLE
class InvMenu not found

### ISSUE THREAD

**Issue by ZenTechnoDev** [Muqsit/InvMenu#45]
```
class 'muqsit\invmenu\InvMenu' not found.
```
While i have the class:
```
use muqsit\invmenu\InvMenu;
```
the code on where the error occured is
```
        return InvMenu::create(InvMenu::TYPE_CHEST)
            ->setName("Trash Can")
            ->sessionize()
            ->setInventoryCloseListener(Trashcan::class . "::dispose");
```

**Comment by JackMD** [comment]
You need to use Devirion to load the classes

**Comment by ZenTechnoDev** [comment]
How?

**Comment by ZenTechnoDev** [comment]
I have Devirion

**Comment by ZenTechnoDev** [comment]
Im new to virions

**Comment by Muqsit** [comment]
Read: https://github.com/poggit/support/blob/master/virion.md#testing-a-virion-or-plugin
You can try the pmmp forums to get help with loading virions. There's actually already a solved thread stating this very issue: https://forums.pmmp.io/threads/invmenu.7303/#post-60484
