### ISSUE TITLE
Inventory Transaction Bug

### ISSUE THREAD

**Issue by iTzFreeHD** [Muqsit/InvMenu#49]
PMMP version 1.12, Release: 3.9.0
Click on a Item in a Chestinventory (don´t close this Inv) -> open a new Chestinventory -> Click on a Item -> Bug it doesn´t work

**Comment by iTzFreeHD** [comment]
The bug isn`t fixed with the #50 update
If you click on Items to chnge the inventory items the items are very buggy

**Comment by Muqsit** [comment]
I have no clue how you were able to test this out on 3.9.0 before InvMenu was made compatible. Anyway, you're referring to #41 which is fixed in the branch which supports API 4.0.0.

**Comment by belohnung** [comment]
same here
