### ISSUE TITLE
Inventory Item / Transaction Bug

### ISSUE THREAD

**Issue by iTzFreeHD** [Muqsit/InvMenu#52]
PMMP: 3.9.0 -> 1.12
Plugins: DeVirion, DevTools, LobbySystem, PermissionsSystem
Video: https://youtu.be/V3Ec9yTEzJ0

On Minecraft 1.11 the chests does work but after the Update Chest didn´t Work fine.
I checked it on: Linux (Ubuntu), Windows 10

**Comment by belohnung** [comment]
same here
