### ISSUE TITLE
Mobile & creative bypasses cancelled transactions

### ISSUE THREAD

**Issue by TwistedAsylumMC** [Muqsit/InvMenu#53]
Returning false in the ``setListener`` callable cancels the transaction, well most the time.
1. Being in creative bypasses this, without having to use any glitch to get items from the inventory, you can just click the item and get it (doesn't work in survival)
2. Pocket users can use the quick swap feature to receive items that are cancelled in the event ([video here](https://imgur.com/XL5Fyck)) Windows 10 users cannot reproduce this issue

Is this an issue with InvMenu, Minecraft or my plugin?

**Comment by Muqsit** [comment]
Can you send steps to reproduce this? I can't reproduce this what-so-ever. (Also send your client version)

**Comment by JaxkDev** [comment]
Im using MysteryCrates but it links with this, I've looked through and it does set it to readOnly() however win10 players can simply click anything in the menu and get it (unable to repro on PE apparently)
