### ISSUE TITLE
Error while starting server

### ISSUE THREAD

**Issue by HimmelKreis4865** [Muqsit/InvMenu#54]
Hello, 
Ich found an error 
`[12:53:40] [Server thread/CRITICAL]: Error: "Class 'pocketmine\network\mcpe\protocol\types\inventory\WindowTypes' not found" (EXCEPTION) in "plugins/LobbyManager/src/muqsit/invmenu/InvMenuHandler" at line 63`
when I try to start the server.

**Comment by HimmelKreis4865** [comment]
ouh there are much more undefined classes in the plugin.

**Comment by Muqsit** [comment]
You are most likely running on PMMP API 3 but are using InvMenu for API 4
https://poggit.pmmp.io/r/62305/InvMenu_dev-70.phar
