### ISSUE TITLE
Crashing when reloading

### ISSUE THREAD

**Issue by ASANITA** [Muqsit/InvMenu#55]
Every time I reload and try to open an double chest inventory it kicks me out of the game.
InvalidStateException: "Tried to schedule Task to disable scheduler" (EXCEPTION) in "src\pocketmine\scheduler\TaskScheduler" at line 148.

**Comment by Muqsit** [comment]
Do you have any plugins that are not loading (or being disabled in a way) on server startup? That may be the culprit.

**Comment by Muqsit** [comment]
Try this build: https://poggit.pmmp.io/r/70989/InvMenu_dev-78.phar
