### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by NxtUser-HD** [Muqsit/InvMenu#59]
Hi there,

Controllers and mobile players can take items from a ChestInventory even though the ChestInventory is readonly, but if you take the item in hand it disappears. Windows 10 players, on the other hand, do not have the bug as long as they try to take the item with shift.

**Comment by Muqsit** [comment]
This isn't a bug with InvMenu, this appears to be happening ever since the release of 1.13 (Windows 10 users can also drop the item using the Q key to select an item).

**Comment by Muqsit** [comment]
https://github.com/pmmp/PocketMine-MP/issues/3226
