### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rjworks** [Muqsit/InvMenu#61]
in the example, the following code is given to register an inventory

public const TYPE_DISPENSER = "myplugin:dispenser";

public function registerCustomMenuTypes() : void{
	$type = new SingleBlockMenuMetadata(
		self::TYPE_DISPENSER, // identifier
		9, // number of slots
		WindowTypes::DISPENSER, // mcpe window type id
		BlockFactory::get(Block::DISPENSER), // Block
		"Dispenser" // block entity identifier
	);
	InvMenuHandler::registerMenuType($menu);
}

$this->registerCustomMenuTypes();
but what is $menu in InvMenuHandler::registerMenuType($menu);

**Comment by Muqsit** [comment]
Ahh my bad, `$menu` was supposed to be `$type`.
