### ISSUE TITLE
err on player manager

### ISSUE THREAD

**Issue by xXNiceYT** [Muqsit/InvMenu#66]
ErrorException: "Undefined index: ??BVW?:!??7?w?8(" (EXCEPTION) in "/server/virions/InvMenu-master/src/muqsit/invmenu/session/PlayerManager" at line 36

**Comment by Muqsit** [comment]
Please send the stack trace

**Comment by xXNiceYT** [comment]
I am not sure how it was caused so sorry I’ll try figure it out and send you

**Comment by Muqsit** [comment]
Alright, I'll be closing this then. Feel free to bump whenever you get a stack trace

**Comment by bulutsun** [comment]
I'm having the same error. Did you find out why it originated?
