### ISSUE TITLE
Nukkit

### ISSUE THREAD

**Issue by zyware** [Muqsit/InvMenu#7]
Maybe worth create branch for Nukkit (https://github.com/NukkitX/Nukkit)? This is a very good and necessary plugin.

**Comment by Muqsit** [comment]
I know the project has a handful active developers but I don't have any plans on working on it or Java in general. Here are my reasons:
-  I have barely worked with anything Java.
- PocketMine's Inventory API is becoming better and better and is comparatively highly extensive.
- Nukkit still uses the old pocketmine Inventory API format with every inventory depending on an InventoryHolder.
- Another branch in a different language than master doesn't make sense.
