### ISSUE TITLE
Open gui from a different script while there is a gui open

### ISSUE THREAD

**Issue by PixelzChris** [Muqsit/InvMenu#71]
When i try to open a menu from a different script it doesnt work. I tried to add command so i can use dispatch command but it didnt work. I also tried to call it from the current script but it didnt work either.

What my code has is: 
A transaction event with a check if the item with the current name has got any action and if it does then i close the current window and i call the other window

What happens?
It just closes the menu

**Comment by Muqsit** [comment]
Can you send your code?

**Comment by PixelzChris** [comment]
`$player->removeWindow($this->shopmenu->getInventory());
                    taggui::$tagmenu->send($player);`
Script is file i dont know if you use script on php but in c# its called script its like the same thing
so script = file (in the same plugin)

**Comment by Muqsit** [comment]
> What my code has is:
A transaction event with a check if the item with the current name has got any action and if it does then i close the current window and i call the other window
> $player->removeWindow($this->shopmenu->getInventory()); taggui::$tagmenu->send($player);
The snippet you sent is completely unrelated to the issue you're facing 🤔

**Comment by Muqsit** [comment]
I can't really work anything out with the lack of information provided. Feel free to bump when you've got it.
