### ISSUE TITLE
API Problem

### ISSUE THREAD

**Issue by dstmaloka** [Muqsit/InvMenu#72]
[Server thread/ERROR]: [DEVirion] Cannot load virion InvMenu: Server has incompatible API version 3.12.0

**Comment by Muqsit** [comment]
Make sure to pick the right one.
The one with the branch name `master` supports API 3
The other one supports API 4
![image](https://user-images.githubusercontent.com/15074389/82686342-27210600-9c6f-11ea-8cc5-d2889c3e592a.png)
