### ISSUE TITLE
Question about shared backpack

### ISSUE THREAD

**Issue by Jkzn** [Muqsit/InvMenu#75]
I have a question, you could make a shared backpack (2 players or more) and that every time someone takes out an item it is updated, to avoid bugs

**Comment by Muqsit** [comment]
By default, all menus are shared. You have to explicitly specify that you want to make copies of the inventory if you need manual synchronization.
```php
// Menu shared
$menu = InvMenu::create(InvMenu::TYPE_CHEST);
$menu->send($player1);
$menu->send($player2);
```
```php
// Menu NOT shared
$menu = InvMenu::createSessionized(InvMenu::TYPE_CHEST);
$menu->send($player1);
$menu->send($player2);
```
Btw, the `InvMenu::createSessionized()` function is currently deprecated and scheduled for removal in the future.
