### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by WEATHERCRAFTYT1** [Muqsit/InvMenu#77]
the plugin does not load becuase of the new 1.16 update. Its doesnt support 3.14.0

**Comment by Muqsit** [comment]
InvMenu wasn't affected by the 1.16 protocol changes.

**Comment by WEATHERCRAFTYT1** [comment]
That’s weird because for me it says Cannot load virion InvMenu: Server was incompatible version 3.14.0

**Comment by Muqsit** [comment]
Hmm are you sure that's what it said? Can you paste the exact error here? Also, make sure you're using InvMenu targeting API 3. The `master` branch targets API 3.x.x while the `4.0` branch targets API 4.x.x
![image](https://user-images.githubusercontent.com/15074389/85959960-2fc8d280-b9b9-11ea-973f-fc968f5c41ae.png)

**Comment by WEATHERCRAFTYT1** [comment]
Ok
