### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by HaiKHGaMer** [Muqsit/InvMenu#89]
i do/gui and click item my server is crash here erorr message and sometimes I do/gui click item my game is Crash
![Untitled](https://user-images.githubusercontent.com/66076787/88374188-84e2e300-cdc3-11ea-8e0b-89d1cd578e7f.png)

**Comment by Muqsit** [comment]
Duplicate of #88

**Comment by HaiKHGaMer** [comment]
how??

**Comment by HaiKHGaMer** [comment]
i dont understand

**Comment by HaiKHGaMer** [comment]
Pls help me I don't understand
