### ISSUE TITLE
how to get the slot that the item was put into?

### ISSUE THREAD

**Issue by rjworks** [Muqsit/InvMenu#92]
```
SlotChangeAction $action
$inventory = $action->getInventory();
var_dump($inventory->getItem( 0 )->getName());
```
I put the item in the inventory, and on the listener, it says the item in the slot where I put the item in is AIr

**Comment by Muqsit** [comment]
Use `$action->getSlot()`. Btw, do not use `$inventory->getItem()` to get back the item because at the time you are listening, the transaction hasn't completed yet.
```php
$menu->setListener(function(Player $player, Item $itemClicked, Item $itemClickedWith, SlotChangeAction $action) : bool{
	$inventory = $action->getInventory();
	$slot = $action->getSlot();
	var_dump($itemClicked);
	return true;
});
```

**Comment by rjworks** [comment]
$action->getSlot() returns slot number but i want the item

**Comment by Muqsit** [comment]
@rjworks `$itemClicked` is the item

**Comment by rjworks** [comment]
how do i get the slot of which $itemClicked is placed?

**Comment by Muqsit** [comment]
$action->getSlot()

**Comment by rjworks** [comment]
> $action->getSlot()

i am face palming, thanks
