### ISSUE TITLE
Integrate InvCrashFix 

### ISSUE THREAD

**Issue by HyperFlareMC** [Muqsit/InvMenu#95]
This request is simple, it integrates the [InvCrashFix](https://github.com/Muqsit/InvCrashFix) plugin into the virion directly. It will remove the dependency of having the additional plugin, while also solving the issue.

**Comment by Muqsit** [comment]
It doesn't make sense to integrate something that should've been integrated in the core software itself.

If it's integrated in InvMenu, server owners would need to have a plugin that depends on InvMenu only to fix inventory crashes. The inventory crashes can't only be caused by InvMenu.
