### ISSUE TITLE
Plugin Dont Register

### ISSUE THREAD

**Issue by laigelplayz** [Muqsit/InvMenu#96]
Plugin is not regestering even tho i put it on the pluginsfolder, also It works when the firstime i put it then now i think because i restart the server its not regestering anymore.....

**Comment by laigelplayz** [comment]
Please Fix....But if its not bc of the plugin can you tell me how to fixed it?

**Comment by Muqsit** [comment]
InvMenu isn't a plugin, it is a library for plugins. If you are a plugin developer, check out [Using in a plugin](https://github.com/Muqsit/InvMenu/wiki/Using-InvMenu-in-a-plugin) and [InvMenu v4.0 Examples](https://github.com/Muqsit/InvMenu/wiki/Examples---InvMenu-v4)
